#!/usr/bin/env python3
"""Build ConceptualPhysicalScienceExplorationsCatalog.swift from TOC data."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "Data/ConceptualPhysicalScienceExplorationsCatalog.swift"

# Table of contents — Conceptual Physical Science Explorations (Hewitt et al.)
PARTS = [
    ("intro", "Front Matter", 0),
    ("p1", "Part One — Mechanics", 15),
    ("p2", "Part Two — Forms of Energy", 165),
    ("p3", "Part Three — Chemistry", 357),
    ("p4", "Part Four — Earth Science", 581),
    ("p5", "Part Five — Astronomy", 765),
]

APPENDICES = [
    ("A", "On Measurement and Unit Conversion", 837),
    ("B", "Linear and Rotational Motion", 840),
    ("C", "Working with Vector Components", 846),
    ("D", "Exponential Growth and Doubling Time", 850),
    ("E", "Safety", 854),
]

# (number, title, part_id, start_page, [(section_id, section_title), ...])
CHAPTERS = [
    (1, "About Science", "intro", 1, [
        ("1.1", "A Brief History of Advances in Science"),
        ("1.2", "Mathematics and Conceptual Physical Science"),
        ("1.3", "Scientific Methods—Classic Tools"),
        ("1.4", "Scientific Hypotheses Must Be Testable"),
        ("1.5", "A Scientific Attitude Underlies Good Science"),
        ("1.6", "The Search for Order—Science, Art, and Religion"),
        ("1.7", "Technology—Practical Use of the Findings of Science"),
        ("1.8", "The Physical Sciences: Physics, Chemistry, Earth Science, and Astronomy"),
        ("1.9", "In Perspective"),
    ]),
    (2, "Newton's First Law of Motion—The Law of Inertia", "p1", 17, [
        ("2.1", "Aristotle's Classification of Motion"),
        ("2.2", "Galileo's Concept of Inertia"),
        ("2.3", "Galileo's Concepts of Speed and Velocity"),
        ("2.4", "Motion Is Relative"),
        ("2.5", "Newton's First Law of Motion—The Law of Inertia"),
        ("2.6", "Net Force—The Combination of All Forces That Act on an Object"),
        ("2.7", "Equilibrium for Objects at Rest"),
        ("2.8", "The Support Force—Why We Don't Fall Through the Floor"),
        ("2.9", "Equilibrium for Moving Objects"),
        ("2.10", "Earth Moves Around the Sun"),
    ]),
    (3, "Newton's Second Law of Motion—Force and Acceleration", "p1", 37, [
        ("3.1", "Galileo Developed the Concept of Acceleration"),
        ("3.2", "Force Causes Acceleration"),
        ("3.3", "Mass Is a Measure of Inertia"),
        ("3.4", "Mass Resists Acceleration"),
        ("3.5", "Newton's Second Law Links Force, Acceleration, and Mass"),
        ("3.6", "Friction Is a Force That Affects Motion"),
        ("3.7", "Objects in Free Fall Have Equal Acceleration"),
        ("3.8", "Newton's Second Law Explains Why Objects in Free Fall Have Equal Acceleration"),
        ("3.9", "Acceleration of Fall Is Less When Air Drag Acts"),
    ]),
    (4, "Newton's Third Law of Motion—Action and Reaction", "p1", 57, [
        ("4.1", "A Force Is Part of an Interaction"),
        ("4.2", "Newton's Third Law—Action and Reaction"),
        ("4.3", "A Simple Rule Helps Identify Action and Reaction"),
        ("4.4", "Action and Reaction on Objects of Different Masses"),
        ("4.5", "Action and Reaction Forces Act on Different Objects"),
        ("4.6", "The Classic Horse-Cart Problem—A Mind Stumper"),
        ("4.7", "Action Equals Reaction"),
        ("4.8", "Summary of Newton's Three Laws"),
    ]),
    (5, "Momentum", "p1", 74, [
        ("5.1", "Momentum Is Inertia in Motion"),
        ("5.2", "Impulse Changes Momentum"),
        ("5.3", "Momentum Is Conserved When No External Force Acts"),
        ("5.4", "Momentum Change Is Greater When Bouncing Occurs"),
        ("5.5", "Conservation of Momentum in Collisions"),
    ]),
    (6, "Energy", "p1", 90, [
        ("6.1", "Work—Force × Distance"),
        ("6.2", "Power—How Quickly Work Gets Done"),
        ("6.3", "Mechanical Energy"),
        ("6.4", "Potential Energy Is Stored Energy"),
        ("6.5", "Kinetic Energy Is Energy of Motion"),
        ("6.6", "Work-Energy Theorem"),
        ("6.7", "Conservation of Energy"),
        ("6.8", "Machines—Devices to Multiply Forces"),
        ("6.9", "Efficiency—A Measure of Work Done for Energy Spent"),
        ("6.10", "Sources of Energy"),
        ("6.11", "Energy for Life"),
    ]),
    (7, "Gravity, Projectiles, and Satellite Motion", "p1", 112, [
        ("7.1", "The Legend of the Falling Apple"),
        ("7.2", "The Fact of the Falling Moon"),
        ("7.3", "Newton's Grandest Discovery—The Law of Universal Gravitation"),
        ("7.4", "Gravity and Distance: The Inverse-Square Law"),
        ("7.5", "The Universal Gravitational Constant, G"),
        ("7.6", "The Mass of the Earth Is Measured"),
        ("7.7", "Projectile Motion"),
        ("7.8", "Fast-Moving Projectiles—Satellites"),
        ("7.9", "Circular Satellite Orbits"),
        ("7.10", "Elliptical Orbits"),
        ("7.11", "Escape Speed"),
    ]),
    (8, "Fluid Mechanics", "p1", 137, [
        ("8.1", "Density—A Measure of Compactness"),
        ("8.2", "Pressure—Force per Area"),
        ("8.3", "Buoyancy in a Liquid"),
        ("8.4", "Archimedes' Principle—Sink or Swim"),
        ("8.5", "Pressure in a Gas"),
        ("8.6", "Atmospheric Pressure Is Due to the Weight of the Atmosphere"),
        ("8.7", "Pascal's Principle—The Transmission of Pressure in a Fluid"),
        ("8.8", "Buoyancy in a Gas—More Archimedes' Principle"),
        ("8.9", "Bernoulli's Principle—Flying with Physics"),
    ]),
    (9, "Heat", "p2", 167, [
        ("9.1", "Thermal Energy—The Total Energy in a Substance"),
        ("9.2", "Temperature—Average Kinetic Energy per Molecule in a Substance"),
        ("9.3", "Absolute Zero—Nature's Lowest Possible Temperature"),
        ("9.4", "Heat Is the Movement of Thermal Energy"),
        ("9.5", "Specific Heat Capacity—A Measure of Thermal Inertia"),
        ("9.6", "Thermal Expansion"),
        ("9.7", "Conduction—Heat Transfer via Particle Collision"),
        ("9.8", "Convection—Heat Transfer via Moving Fluids"),
        ("9.9", "Radiation—Heat Transfer via Radiant Energy"),
        ("9.10", "Energy Changes with Change of Phase"),
    ]),
    (10, "Electricity", "p2", 192, [
        ("10.1", "Electric Charge Is a Basic Characteristic of Matter"),
        ("10.2", "Coulomb's Law—The Force Between Charged Particles"),
        ("10.3", "Electric Polarization"),
        ("10.4", "Electric Current—The Flow of Electric Charge"),
        ("10.5", "An Electric Circuit Is Produced by Electrical Pressure—Voltage"),
        ("10.6", "Electrical Resistance"),
        ("10.7", "Ohm's Law—The Relationship Among Current, Voltage, and Resistance"),
        ("10.8", "Electric Shock"),
        ("10.9", "Direct Current and Alternating Current"),
        ("10.10", "Electric Power—The Rate of Doing Work"),
        ("10.11", "Electric Circuits—Series and Parallel"),
    ]),
    (11, "Magnetism", "p2", 216, [
        ("11.1", "Magnetic Poles—Attraction and Repulsion"),
        ("11.2", "Magnetic Fields—Regions of Magnetic Influence"),
        ("11.3", "Magnetic Domains—Clusters of Aligned Atoms"),
        ("11.4", "The Interaction Between Electric Currents and Magnetic Fields"),
        ("11.5", "Magnetic Forces Are Exerted on Moving Charges"),
        ("11.6", "Electromagnetic Induction—How Voltage Is Created"),
        ("11.7", "Faraday's Law"),
        ("11.8", "Power Production and Stepping Current and Voltage with Transformers"),
        ("11.9", "The Induction of Fields—Both Electric and Magnetic"),
    ]),
    (12, "Waves and Sound", "p2", 235, [
        ("12.1", "Special Wiggles—Vibrations and Waves"),
        ("12.2", "Wave Motion—Transporting Energy"),
        ("12.3", "Wave Speed"),
        ("12.4", "Sound Travels in Longitudinal Waves"),
        ("12.5", "Speed of Sound"),
        ("12.6", "Sound Can Be Reflected and Refracted"),
        ("12.7", "Forced Vibrations and Natural Frequency"),
        ("12.8", "Resonance—Adding Waves in Synchronization"),
        ("12.9", "Interference—Wave Addition and Subtraction"),
        ("12.10", "The Doppler Effect—Changes in Frequency due to Motion"),
        ("12.11", "Wave Barriers and Bow Waves"),
        ("12.12", "Shock Waves and the Sonic Boom"),
    ]),
    (13, "Light, Reflection, and Color", "p2", 260, [
        ("13.1", "The Electromagnetic Spectrum—and the Tiny Bit That Is Light"),
        ("13.2", "Why Materials Are Either Transparent or Opaque"),
        ("13.3", "Reflection of Light"),
        ("13.4", "Refraction—The Bending of Light Due to Changing Speed"),
        ("13.5", "Rainbows and Mirages Are Caused by Refraction"),
        ("13.6", "Color Science"),
        ("13.7", "Mixing Colored Lights"),
        ("13.8", "Mixing Colored Pigments"),
        ("13.9", "Why the Sky Is Blue"),
        ("13.10", "Why Sunsets Are Red"),
        ("13.11", "Why Clouds Are White"),
    ]),
    (14, "Properties of Light", "p2", 287, [
        ("14.1", "Light Dispersion and Rainbows"),
        ("14.2", "Lenses"),
        ("14.3", "Image Formation by a Lens"),
        ("14.4", "Diffraction—The Spreading of Light"),
        ("14.5", "Interference—Constructive and Destructive"),
        ("14.6", "Interference Colors by Reflection from Thin Films"),
        ("14.7", "Polarization—Evidence for the Transverse Wave Nature of Light"),
        ("14.8", "Wave-Particle Duality—Two Sides of the Same Coin"),
    ]),
    (15, "The Atom", "p2", 315, [
        ("15.1", "Discovering the Invisible Atom"),
        ("15.2", "Elements and the Periodic Table"),
        ("15.3", "The Atomic Nucleus Consists of Protons and Neutrons"),
        ("15.4", "Isotopes and Atomic Mass"),
        ("15.5", "Electron Shells—Regions About the Nucleus Where Electrons Are Located"),
    ]),
    (16, "Nuclear Energy", "p2", 334, [
        ("16.1", "Radioactivity—The Disintegration of the Atomic Nucleus"),
        ("16.2", "Alpha, Beta, and Gamma Rays"),
        ("16.3", "Environmental Radiation"),
        ("16.4", "Transmutation of Elements—Changing Identities"),
        ("16.5", "Half-Life Is a Measure of Radioactive Decay Rate"),
        ("16.6", "Nuclear Fission—The Breaking Apart of Atomic Nuclei"),
        ("16.7", "The Mass-Energy Relationship: E = mc²"),
        ("16.8", "The Chain Reaction of Matter"),
        ("16.9", "Nuclear Fusion—The Combining of Atomic Nuclei"),
    ]),
    (17, "Elements of Chemistry", "p3", 359, [
        ("17.1", "Chemistry Is Known as the Central Science"),
        ("17.2", "The Submicroscopic World Is Super-Small"),
        ("17.3", "The Phase of Matter Can Change"),
        ("17.4", "Matter Has Physical and Chemical Properties"),
        ("17.5", "Determining Physical and Chemical Changes Can Be Difficult"),
        ("17.6", "The Periodic Table Helps Us to Understand the Elements"),
        ("17.7", "Elements Can Combine to Form Compounds"),
        ("17.8", "There Is a System for Naming Compounds"),
    ]),
    (18, "How Atoms Bond and Molecules Attract", "p3", 384, [
        ("18.1", "Electron-Dot Structures Help Us to Understand Bonding"),
        ("18.2", "Atoms Can Lose or Gain Electrons to Become Ions"),
        ("18.3", "Ionic Bonds Result from a Transfer of Electrons"),
        ("18.4", "Metal Atoms Bond by Losing Their Electrons"),
        ("18.5", "Covalent Bonds Result from a Sharing of Electrons"),
        ("18.6", "Electrons May Be Shared Unevenly in a Covalent Bond"),
        ("18.7", "Polar Molecules Are Shared Unevenly in a Polar Molecule"),
        ("18.8", "Molecules Are Attractive"),
    ]),
    (19, "How Chemicals Mix", "p3", 412, [
        ("19.1", "Most Materials Are Mixtures"),
        ("19.2", "The Chemist's Classification of Matter"),
        ("19.3", "A Solution Is a Single-Phase Homogeneous Mixture"),
        ("19.4", "Concentration Is Given as Moles per Liter"),
        ("19.5", "Solubility Measures How Well a Solute Dissolves"),
        ("19.6", "Soaps Work by Being Both Polar and Nonpolar"),
        ("19.7", "Purifying the Water We Drink"),
    ]),
    (20, "How Chemicals React", "p3", 437, [
        ("20.1", "Chemical Reactions Are Represented by Chemical Equations"),
        ("20.2", "Chemical Reactions Can Be Slow or Fast; Activation Energy Is the Energy Needed for Reactants to React"),
        ("20.3", "Catalysts Speed Up Chemical Reactions"),
        ("20.4", "Chemical Reactions Can Be Either Exothermic or Endothermic"),
        ("20.5", "Chemical Reactions Are Driven by Entropy"),
    ]),
    (21, "Two Types of Chemical Reactions", "p3", 460, [
        ("21.1", "Acids Donate and Bases Accept Hydrogen Ions"),
        ("21.2", "Some Acids and Bases Are Stronger Than Others"),
        ("21.3", "Solutions Can Be Acidic, Basic, or Neutral; the pH Scale Is Used to Describe Acidity"),
        ("21.4", "Rainwater Is Acidic, and Ocean Water Is Basic"),
        ("21.5", "Oxidation Is the Loss of Electrons and Reduction Is the Gain of Electrons"),
        ("21.6", "The Energy of Flowing Electrons Can Be Harnessed"),
        ("21.7", "Oxidation Is Responsible for Corrosion and Combustion"),
        ("21.8", "Hydrogen Is a Possible Clean-Burning Fuel"),
    ]),
    (22, "Organic Compounds", "p3", 490, [
        ("22.1", "Hydrocarbons Contain Only Carbon and Hydrogen"),
        ("22.2", "Unsaturated Hydrocarbons Contain Multiple Bonds"),
        ("22.3", "Functional Groups Give Organic Compounds Their Distinctive Properties"),
        ("22.4", "Alcohols, Phenols, and Ethers"),
        ("22.5", "Amines and Alkaloids"),
        ("22.6", "Carbonyl Compounds"),
        ("22.7", "Polymers"),
    ]),
    (23, "The Nutrients of Life", "p3", 521, [
        ("23.1", "Biomolecules Are Produced and Used by Organisms"),
        ("23.2", "Carbohydrates Give Structure and Energy"),
        ("23.3", "Lipids Are Insoluble in Water"),
        ("23.4", "Proteins Are Polymers of Amino Acids"),
        ("23.5", "Nucleic Acids Code for Proteins"),
        ("23.6", "Vitamins Are Organic; Minerals Are Inorganic"),
        ("23.7", "Metabolism Is the Cycling of Biomolecules Through the Body"),
    ]),
    (24, "Medicinal Chemistry", "p3", 554, [
        ("24.1", "Medicines Are Drugs That Benefit the Body"),
        ("24.2", "The Lock-and-Key Model Guides Chemists in Creating New Medicines"),
        ("24.3", "Chemotherapy Cures the Host by Killing the Disease"),
        ("24.4", "The Nervous System Is a Network of Neurons"),
        ("24.5", "Psychoactive Drugs Alter the Mind or Behavior"),
        ("24.6", "Pain Relievers Inhibit the Transmission or Perception of Pain"),
    ]),
    (25, "Rocks and Minerals", "p4", 583, [
        ("25.1", "Our Rocky Planet"),
        ("25.2", "What Is a Mineral?"),
        ("25.3", "Mineral Properties"),
        ("25.4", "Classification of Rock-Forming Minerals"),
        ("25.5", "The Formation of Minerals and Rock"),
        ("25.6", "Rocks Are Divided into Three Main Groups"),
        ("25.7", "Igneous Rocks Form When Magma Cools"),
        ("25.8", "Sedimentary Rocks Blanket Most of Earth's Surface"),
        ("25.9", "Metamorphic Rocks Are Changed Rocks"),
        ("25.10", "The Rock Cycle"),
    ]),
    (26, "The Architecture of Earth", "p4", 616, [
        ("26.1", "Earthquakes Make Seismic Waves"),
        ("26.2", "Seismic Waves Reveal Earth's Internal Layers"),
        ("26.3", "Internal Motion Deforms Earth's Surface"),
    ]),
    (27, "Plate Tectonics—A Unifying Theory", "p4", 638, [
        ("27.1", "Continental Drift—An Idea Before Its Time"),
        ("27.2", "Search for the Mechanism to Support Continental Drift"),
        ("27.3", "The Theory of Plate Tectonics"),
        ("27.4", "Three Types of Plate Boundaries"),
        ("27.5", "The Theory That Explains Much"),
    ]),
    (28, "Shaping Earth's Surface", "p4", 660, [
        ("28.1", "The Hydrologic Cycle"),
        ("28.2", "Groundwater—Water Below the Surface"),
        ("28.3", "The Work of Groundwater"),
        ("28.4", "Surface Water and Rivers—Water at Earth's Surface"),
        ("28.5", "The Work of Surface Water"),
        ("28.6", "Glaciers and Glaciation—Earth's Frozen Water"),
        ("28.7", "The Work of Glaciers"),
        ("28.8", "The Work of Air"),
    ]),
    (29, "Geologic Time—Reading the Rock Record", "p4", 690, [
        ("29.1", "Relative Dating—The Placement of Rocks in Order"),
        ("29.2", "Radiometric Dating Reveals the Actual Time of Rock Formation"),
        ("29.3", "Geologic Time"),
        ("29.4", "Precambrian Time—A Time of Hidden Life"),
        ("29.5", "The Paleozoic Era—A Time of Life Diversification"),
        ("29.6", "The Mesozoic Era—The Age of Reptiles"),
        ("29.7", "The Cenozoic Era—The Age of Mammals"),
        ("29.8", "Earth History in a Capsule"),
    ]),
    (30, "The Atmosphere, the Oceans, and Their Interactions", "p4", 715, [
        ("30.1", "Components of Earth's Atmosphere"),
        ("30.2", "Vertical Structure of the Atmosphere"),
        ("30.3", "Solar Energy"),
        ("30.4", "Driving Forces of Air Motion"),
        ("30.5", "Global Atmospheric Circulation Patterns"),
        ("30.6", "Components of Earth's Oceans"),
        ("30.7", "Oceanic Circulation"),
    ]),
    (31, "Weather", "p4", 741, [
        ("31.1", "Water in the Atmosphere"),
        ("31.2", "Weather Variables"),
        ("31.3", "There Are Many Different Clouds"),
        ("31.4", "Air Masses, Fronts, and Storms"),
        ("31.5", "Weather Can Be Violent"),
        ("31.6", "The Weather—Number-One Topic of Conversation"),
    ]),
    (32, "The Solar System", "p5", 767, [
        ("32.1", "The Solar System Is Mostly Empty Space"),
        ("32.2", "Solar Systems Form from Nebula"),
        ("32.3", "The Sun Is Our Prime Source of Energy"),
        ("32.4", "The Inner Planets Are Rocky"),
        ("32.5", "The Outer Planets Are Gaseous"),
        ("32.6", "Earth's Moon"),
        ("32.7", "Failed Planet Formation"),
    ]),
    (33, "Stars", "p5", 796, [
        ("33.1", "Observing the Night Sky"),
        ("33.2", "Stars Have Different Brightness and Color"),
        ("33.3", "The Hertzsprung-Russell Diagram Describes Stars"),
        ("33.4", "The Life Cycles of Stars"),
        ("33.5", "Novae and Supernovae Are Stellar Explosions"),
        ("33.6", "Supergiant Stars Collapse into Black Holes"),
    ]),
    (34, "Galaxies and the Cosmos", "p5", 816, [
        ("34.1", "A Galaxy Is an Island of Stars"),
        ("34.2", "Elliptical, Spiral, and Irregular Galaxies"),
        ("34.3", "Active Galaxies Emit Huge Amounts of Energy"),
        ("34.4", "Galaxies Form Clusters and Superclusters"),
        ("34.5", "Galaxies Are Moving Away from One Another"),
        ("34.6", "Further Evidence for the Big Bang"),
        ("34.7", "Dark Matter Is Invisible"),
        ("34.8", "Dark Energy Opposes Gravity"),
    ]),
]


def swift_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_swift() -> str:
    lines = [
        "import Foundation",
        "",
        "/// Conceptual Physical Science Explorations — official part/chapter/section index from the textbook TOC.",
        "enum ConceptualPhysicalScienceExplorationsCatalog {",
        "    struct PartInfo: Hashable {",
        "        let id: String",
        "        let name: String",
        "        let startPage: Int",
        "    }",
        "",
        "    struct Section: Hashable {",
        "        let id: String",
        "        let title: String",
        "    }",
        "",
        "    struct Chapter: Hashable {",
        "        let number: Int",
        "        let title: String",
        "        let part: PartInfo",
        "        let startPage: Int",
        "        let sections: [Section]",
        "    }",
        "",
        "    struct Appendix: Hashable {",
        "        let letter: String",
        "        let title: String",
        "        let startPage: Int",
        "    }",
        "",
        '    static let editionTitle = "Conceptual Physical Science Explorations (Hewitt et al.)"',
        "",
        "    private static let parts: [PartInfo] = [",
    ]
    for pid, name, page in PARTS:
        lines.append(f'        PartInfo(id: "{pid}", name: "{swift_string(name)}", startPage: {page}),')
    lines.append("    ]")
    lines.append("")
    lines.append("    private static let partByID: [String: PartInfo] = {")
    lines.append("        Dictionary(uniqueKeysWithValues: parts.map { ($0.id, $0) })")
    lines.append("    }()")
    lines.append("")
    lines.append("    static let appendices: [Appendix] = [")
    for letter, title, page in APPENDICES:
        lines.append(f'        Appendix(letter: "{letter}", title: "{swift_string(title)}", startPage: {page}),')
    lines.append("    ]")
    lines.append("")
    lines.append("    static let chapters: [Chapter] = [")

    part_lookup = {p[0]: p for p in PARTS}
    for num, title, part_id, page, sections in CHAPTERS:
        part_name = part_lookup[part_id][1]
        sec_lines = ", ".join(
            f'Section(id: "{swift_string(sid)}", title: "{swift_string(stitle)}")'
            for sid, stitle in sections
        )
        lines.append(
            f'        Chapter(number: {num}, title: "{swift_string(title)}", '
            f'part: partByID["{part_id}"]!, startPage: {page}, sections: [{sec_lines}]),'
        )

    lines.extend([
        "    ]",
        "",
        "    private static let byNumber: [Int: Chapter] = {",
        "        Dictionary(uniqueKeysWithValues: chapters.map { ($0.number, $0) })",
        "    }()",
        "",
        "    private static let appendixByLetter: [String: Appendix] = {",
        "        Dictionary(uniqueKeysWithValues: appendices.map { ($0.letter, $0) })",
        "    }()",
        "",
        "    static func chapter(_ number: Int) -> Chapter? {",
        "        byNumber[number]",
        "    }",
        "",
        "    static func appendix(_ letter: String) -> Appendix? {",
        "        appendixByLetter[letter.uppercased()]",
        "    }",
        "",
        "    /// Formats `1`, `2–4`, `10–13`, `1 + App. B`, or `16 · 24`.",
        "    static func formatReference(_ chapterPart: String) -> String {",
        "        var labels: [String] = []",
        "        let normalized = chapterPart",
        "            .replacingOccurrences(of: \"Ch \", with: \"\")",
        "            .trimmingCharacters(in: .whitespaces)",
        "",
        "        if normalized.contains(\"App.\") {",
        "            let segments = normalized.split(separator: \"+\", omittingEmptySubsequences: true)",
        "            for segment in segments {",
        "                let piece = segment.trimmingCharacters(in: .whitespaces)",
        "                if piece.lowercased().contains(\"app.\") {",
        "                    let letter = piece",
        "                        .replacingOccurrences(of: \"App.\", with: \"\")",
        "                        .replacingOccurrences(of: \"Appendix\", with: \"\")",
        "                        .trimmingCharacters(in: .whitespaces)",
        "                    if let appendix = appendix(letter) {",
        "                        labels.append(\"Appendix \\(appendix.letter) — \\(appendix.title)\")",
        "                    } else {",
        "                        labels.append(piece)",
        "                    }",
        "                } else {",
        "                    labels.append(formatChapterNumbers(piece))",
        "                }",
        "            }",
        "            return labels.joined(separator: \" · \")",
        "        }",
        "",
        "        return formatChapterNumbers(normalized)",
        "    }",
        "",
        "    private static func formatChapterNumbers(_ chapterPart: String) -> String {",
        "        let numbers = parseChapterNumbers(chapterPart)",
        "        guard !numbers.isEmpty else { return \"Ch \\(chapterPart)\" }",
        "        return numbers.compactMap { number in",
        "            guard let ch = chapter(number) else { return \"Ch \\(number)\" }",
        "            return \"\\(ch.part.name) · Ch \\(ch.number) — \\(ch.title)\"",
        "        }.joined(separator: \" · \")",
        "    }",
        "",
        "    static func parseChapterNumbers(_ chapterPart: String) -> [Int] {",
        "        var result: [Int] = []",
        "        let normalized = chapterPart",
        "            .replacingOccurrences(of: \"Ch \", with: \"\")",
        "            .trimmingCharacters(in: .whitespaces)",
        "",
        "        for segment in normalized.split(separator: \"·\").map({ $0.trimmingCharacters(in: .whitespaces) }) {",
        "            if segment.contains(\"–\") {",
        "                let bounds = segment.split(separator: \"–\").compactMap { Int($0.trimmingCharacters(in: .whitespaces)) }",
        "                if bounds.count == 2, bounds[0] <= bounds[1] {",
        "                    result.append(contentsOf: bounds[0]...bounds[1])",
        "                    continue",
        "                }",
        "            }",
        "            if segment.contains(\"-\") && !segment.contains(\"–\") {",
        "                let bounds = segment.split(separator: \"-\").compactMap { Int($0.trimmingCharacters(in: .whitespaces)) }",
        "                if bounds.count == 2, bounds[0] <= bounds[1] {",
        "                    result.append(contentsOf: bounds[0]...bounds[1])",
        "                    continue",
        "                }",
        "            }",
        "            if let n = Int(segment) {",
        "                result.append(n)",
        "            }",
        "        }",
        "        return result",
        "    }",
        "",
        "    static func formattedLine(chapter: String, title: String) -> String {",
        "        \"\\(editionTitle) — \\(formatReference(chapter)) — \\(title)\"",
        "    }",
        "",
        "    /// Chapters grouped by part (for Topics reference).",
        "    static var chaptersGroupedByPart: [(part: PartInfo, chapters: [Chapter])] {",
        "        var seen = Set<String>()",
        "        var groups: [(PartInfo, [Chapter])] = []",
        "        for chapter in chapters {",
        "            if seen.insert(chapter.part.id).inserted {",
        "                groups.append((chapter.part, chapters.filter { $0.part.id == chapter.part.id }))",
        "            }",
        "        }",
        "        return groups",
        "    }",
        "",
        "    static func chaptersGroupedByPart(filterPartIDs: Set<String>) -> [(part: PartInfo, chapters: [Chapter])] {",
        "        chaptersGroupedByPart.filter { filterPartIDs.contains($0.part.id) }",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main():
    OUT.write_text(emit_swift())

    py_out = ROOT / "Scripts/expl_chapters_data.py"
    py_lines = [
        '"""Auto-generated from build_expl_catalog.py — do not edit by hand."""',
        "",
        "EXP_CH: dict[int, tuple[str, str]] = {",
    ]
    for num, title, part_id, _page, _sections in CHAPTERS:
        part_name = next(p[1] for p in PARTS if p[0] == part_id)
        py_lines.append(f'    {num}: ("{part_name}", "{title}"),')
    py_lines.extend([
        "}",
        "",
        "EXP_APPENDIX = {",
    ])
    for letter, title, _page in APPENDICES:
        py_lines.append(f'    "{letter}": "{title}",')
    py_lines.extend([
        "}",
        "",
        "def expl(*parts: str) -> str:",
        '    """Format Expl refs: expl("17"), expl("2", "4"), expl("1 + App. B")."""',
        "    if not parts:",
        '        return ""',
        "    if len(parts) == 1:",
        "        return _expl_single(parts[0])",
        '    return " · ".join(_expl_single(p) for p in parts)',
        "",
        "def _expl_single(chapter_spec: str) -> str:",
        "    parts: list[str] = []",
        '    spec = chapter_spec.replace("Ch ", "").strip()',
        '    if "App." in spec:',
        '        for segment in spec.split("+"):',
        "            piece = segment.strip()",
        '            if "App." in piece:',
        '                letter = piece.replace("App.", "").replace("Appendix", "").strip()',
        "                title = EXP_APPENDIX.get(letter, piece)",
        '                parts.append(f"Appendix {letter} — {title}")',
        "            else:",
        "                parts.extend(_format_chapter_piece(piece))",
        '        return " · ".join(parts)',
        "    labels = _format_chapter_piece(spec)",
        '    return " · ".join(labels)',
        "",
        "def _format_chapter_piece(piece: str) -> list[str]:",
        "    labels: list[str] = []",
        '    for segment in piece.split("·"):',
        "        segment = segment.strip()",
        '        if "–" in segment or "-" in segment:',
        '            sep = "–" if "–" in segment else "-"',
        "            start, end = segment.split(sep, 1)",
        "            for n in range(int(start.strip()), int(end.strip()) + 1):",
        "                labels.append(_chapter_label(n))",
        "        elif segment.isdigit():",
        "            labels.append(_chapter_label(int(segment)))",
        "    return labels if labels else [piece]",
        "",
        "def _chapter_label(n: int) -> str:",
        "    part, title = EXP_CH[n]",
        '    return f"{part} · Ch {n} — {title}"',
        "",
    ])
    py_out.write_text("\n".join(py_lines))
    print(f"Wrote {py_out}")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
